### ISSUE TITLE
Шип Тест Ивент Мо Мент

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#27]
## Описание

Проведение ивента "Шиптест" где на примере крутых шаттлобаталий показывается превосходство СС14 над всем старым и ненужным.

В рамках ивента игроки будут защищать флаги на своих базах от воровства этих флагов врагами на кораблях из космических досок.

Пока как минимум TO-DO список не будет выполнен запускать ивент смысла мало.

## Цель

Завлечение аудитории и демонстрация превосходства двикжа.

## TO-DO:
- [ ] Пушки/турели позволяющие дамажить летающие шаттлы. Делятся на кинематические-снаряды и хитскан-лазеры. Лазеры дамажат точечно, снаряды по площади, но от них (в теории) можно увернуться.
- [ ] Карта состоящая из 4 баз, на каждой по 2 шаттла, свободного пространства для мочилова, и каких-то микроинтересных мест.
- [ ] Система захвата флагов, при захвате флага команда чей флаг захватили теряет респавн - и если кого-то из них убить - они выбывают из игры, иначе респавнятся на флаге.

## Качество Жизни И Геймплея (Долговременные цели)
- [ ] Разные виды топлива. От топлива зависит выработка энергии, расход на метр полёта, и цена.
- [ ] Разные виды двигателей, какой-то креативный способ сборки и ремонта оных. От вида двигателей зависит потреблении энергии, предельная скорость, взрывоустойчивость/опасность(некоторые движки могут рандомно бахать и нужен механик что их чинит)

**Comment by KIBORG04** [comment]
Небольшое ТЗ для шаттло-пушек. 

<details>
<summary>Идеальная фича емае мама закодь!!!</summary>

1. Компонента турели + система
2. Компонента контейнера под пушку в турели + интеграция с системой турели
3. Компонента консоли + система. Включает привязку турелей к консоли. Опционально бинды.
4. Интерфейс для консоли + интеграция с системой турели
5. Окно для консоли
6. Переработка интерфейса радара с преобразованием клика по интерфейсу в угл (что я хз пока что)
7. Для радара показывать полёт снарядов. НАСЛЕДОВАНИЕ ЮЗЕР-ИНТЕРФЕЙСОВ ЗАПРЕЩЕНО.
8. Специальные пушки для турели. Точнее, специальное поведение для патронов: медленные бабахи и лазерки бабахи.
9. (Опционально) синхронизировать поворот турели за движением мышки по интернету
10. (Опционально) ИИ 

</details>

<details>
<summary>Очень простое и самое реалистичное</summary>

1. Сделать для компоненты эмиттеров настройку прожектайлов, потреблением энергии и кд между выстрелами
2. Сделать несколько разных энтити с разными эмиттер-компонентами, снарядами и спрайтами
3. Сделать разные виды прожектайлов. От бабах, до лазерок, до пулеметов?
4. (Опционально) показывать на радаре медленные снаряды.

</details>
